# Generated by Django 5.0.1 on 2024-03-07 10:18

import utils.utils_time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('register_time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('login_time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='api_user_name_03b419_idx')],
            },
        ),
    ]
